rdrf/explorer/urls.py
from django.conf.urls import patterns, url
from explorer.views import MainView
from explorer.views import QueryView, NewQueryView
from explorer.views import DeleteQueryView, DownloadQueryView
from explorer.views import SqlQueryView

urlpatterns = patterns(
    '',
    url(r'^query/(?P<query_id>\w+)/?$',
        QueryView.as_view(), name='explorer_query'),
    url(r'^query/download/(?P<query_id>\w+)/?$',
        DownloadQueryView.as_view(), name='explorer_query_download'),
    url(r'^query/delete/(?P<query_id>\w+)/?$',
        DeleteQueryView.as_view(), name='explorer_query_delete'),
    
    url(r'^sql$',
        SqlQueryView.as_view(), name='explorer_sql_query'),

    url(r'^new$', NewQueryView.as_view(), name='explorer_new'),

    url(r'$', MainView.as_view(), name='explorer_main'),
)

rdrf/rdrf/urls.py
from __future__ import absolute_import
from django.conf.urls import patterns, url, include
from django.conf import settings
from django.contrib import admin
from django.shortcuts import render_to_response
import registry.urls as common_urls
import rdrf.views as views
import rdrf.form_view as form_view
import rdrf.registry_view as registry_view
import rdrf.landing_view as landing_view
import rdrf.import_registry_view as import_registry_view
import rdrf.rest_interface as rest_interface
import rdrf.hgvs_view as hgvs_view
import rdrf.patient_view as patient_view
import rdrf.parent_view as parent_view
import rdrf.login_router as login_router
import rdrf.report_view as report_view
from rdrf.lookup_views import GeneView, LaboratoryView, StateLookup, ClinitianLookup
from ajax_select import urls as ajax_select_urls
from rdrf.views import RegistryList
from registry.patients.views import update_session
from tastypie.api import Api
from rdrf.api import PatientResource

from rdrf.migration_view import MigrationView

from django.views.generic.base import TemplateView
from registration.backends.default.views import ActivationView
#from registration.backends.default.views import RegistrationView

from rdrf.registration_rdrf import RdrfRegistrationView
from rdrf.registry_list_view import RegistryListView

admin.autodiscover()  # very important so that registry admins (genetic, patient, etc) are discovered.


def handler404(request):
    return render_to_response("error/404.html")


def handler500(request):
    return render_to_response("error/500.html")


def handlerApplicationError(request):
    return render_to_response("rdrf_cdes/application_error.html", {"application_error": "Example config Error"})


# TastyPie API
v1_api = Api(api_name='v1')
v1_api.register(PatientResource())


urlpatterns = patterns('',
                       url(r'^test404', handler404),
                       url(r'^test500', handler500),
                       url(r'^testAppError', handlerApplicationError),
                       url(r'^constructors/(?P<form_name>\w+)/?$', form_view.ConstructorFormView.as_view(), name="constructors"),
                       url(r'^rpc', form_view.RPCHandler.as_view(), name='rpc'),

                       (r'^admin/', include(admin.site.urls)),
                       (r'', include('django.contrib.auth.urls')),
                       (r'', include(common_urls, namespace="registry")),
                       
                       url(r'^/?$', landing_view.LandingView.as_view(), name='landing'),
                       url(r'^reglist/?', RegistryListView.as_view(), name="reglist"),
                       url(r'^import/?', import_registry_view.ImportRegistryView.as_view(), name='import_registry'),
                       url(r'^reports/?', report_view.ReportView.as_view(), name="reports"),
                       url(r'^explorer/', include('explorer.urls')),
                       url(r'^gene/?$', GeneView.as_view(), name='gene_source'),
                       url(r'^laboratory/?$', LaboratoryView.as_view(), name='laboratory_source'),

                       url(r'^hgvs/?$', hgvs_view.HGVSView.as_view(), name='hgvs_validator'),
                       url(r'^listregistry/?$', RegistryList.as_view(), name='registry_list'),
                       
                       url(r'^patientslisting/?', form_view.PatientsListingView.as_view(), name="patientslisting"),
                       url(r'^bootgridapi', form_view.BootGridApi.as_view()),

                       
                       url(r'^login/?$', 'django.contrib.auth.views.login', {'template_name': 'admin/login.html'}, name='login'),
                       url(r'^router/', login_router.RouterView.as_view(), name="login_router"),
                       
                       url(r"^(?P<registry_code>\w+)/forms/(?P<form_id>\w+)/(?P<patient_id>\d+)$",
                           form_view.FormView.as_view(), name='registry_form'),
                       url(r"^(?P<registry_code>\w+)/?$", registry_view.RegistryView.as_view(), name='registry'),
                       
                       url(r"^(?P<registry_code>\w+)/patient/?$",
                           patient_view.PatientView.as_view(), name='patient_page'),
                       url(r"^(?P<registry_code>\w+)/patient/(?P<patient_id>\d+)/?$",
                           patient_view.PatientEditView.as_view(), name='patient_edit'),
                       
                       url(r"^(?P<registry_code>\w+)/parent/?$",
                           parent_view.ParentView.as_view(), name='parent_page'),
                       
                       url(r'^(?P<registry_code>\w+)/questionnaire/(?P<questionnaire_context>\w+)?$',
                           form_view.QuestionnaireView.as_view(), name='questionnaire'),
                       url(r'^(?P<registry_code>\w+)/approval/(?P<questionnaire_response_id>\d+)/?$', form_view.QuestionnaireResponseView.as_view(),
                           name='questionnaire_response'),
                       url(r'^(?P<registry_code>\w+)/uploads/(?P<gridfs_file_id>\w+)$',
                           form_view.FileUploadView.as_view(), name='file_upload'),
                       url(r'^(?P<registry_code>\w+)/patients/(?P<patient_id>\d+)?/(?P<form_name>.+?)/(?P<section_code>.+?)/(?P<cde_code>.+?)/?$',
                           rest_interface.RDRFEndpointView.as_view(), name='rest_cde_interface'),
                       url(r'^(?P<registry_code>\w+)/patients/(?P<patient_id>\d+)?/(?P<form_name>.+?)/(?P<section_code>.+?)/?$',
                           rest_interface.RDRFEndpointView.as_view(), name='rest_section_interface'),
                       url(r'^(?P<registry_code>\w+)/patients/(?P<patient_id>\d+)?/(?P<form_name>.+?)/?$',
                           rest_interface.RDRFEndpointView.as_view(), name='rest_form_interface'),
                       url(r'^(?P<registry_code>\w+)/patients/(?P<patient_id>\d+)?/?$',
                           rest_interface.RDRFEndpointView.as_view(), name='rest_interface'),
                       (r'^admin/lookups/', include(ajax_select_urls)),

                       url(r'^admin/patients/updatesession/?$', update_session, name='updatesession'),
                       (r'^api/', include(v1_api.urls)),
                       url(r'^state/(?P<country_code>\w+)/?$', StateLookup.as_view(), name='state_lookup'),
                       url(r'^questionnaireconfig/(?P<form_pk>\d+)/?$',
                           form_view.QuestionnaireConfigurationView.as_view(), name='questionnaire_config'),
                       url(r'^designer/(?P<reg_pk>\d+)$', form_view.RDRFDesigner.as_view(), name='rdrf_designer'),
                       url(r'^cdes', form_view.RDRFDesignerCDESEndPoint.as_view(), name='rdrf_designer_cdes_endpoint'),
                       url(r'^registrystructure/(?P<reg_pk>\d+)$', form_view.RDRFDesignerRegistryStructureEndPoint.as_view(),
                           name='rdrf_designer_registry_structure_endpoint'),
                       url(r'^adjudicationinitiation/(?P<def_id>\d+)/(?P<patient_id>\d+)/?$',
                           form_view.AdjudicationInitiationView.as_view(), name='adjudication_initiation'),
                       url(r'^adjudicationrequest/(?P<adjudication_request_id>\d+)/?$',
                           form_view.AdjudicationRequestView.as_view(), name='adjudication_request'),
                       url(r'^adjudicationresult/(?P<adjudication_definition_id>\d+)/(?P<requesting_user_id>\d+)/(?P<patient_id>\d+)/?$',
                           form_view.AdjudicationResultsView.as_view(), name='adjudication_result'),

                       url(r'^api/clinitian/',
                            ClinitianLookup.as_view(), name="clinician_lookup"),
                       )

urlpatterns += patterns('',
                       url(r'^(?P<registry_code>\w+)/register/$', RdrfRegistrationView.as_view(), name='registration_register'),
                       url(r'^register/complete/$', TemplateView.as_view(template_name='registration/registration_complete.html'), name='registration_complete'),
                       url(r'^register/closed/$', TemplateView.as_view(template_name='registration/registration_closed.html'), name='registration_disallowed'),

                       url(r'^activate/complete/$', TemplateView.as_view(template_name='registration/activation_complete.html'), name='registration_activation_complete'),
                       url(r'^activate/(?P<activation_key>\w+)/$', ActivationView.as_view(), name='registration_activate'),
                       )

urlpatterns += patterns('',
                        url(r'^i18n', include('django.conf.urls.i18n')),
                        )

# pattern for serving statically
if settings.DEBUG:
    urlpatterns += patterns('',
                            (r'^static/(?P<path>.*)$', 'django.views.static.serve',
                             {'document_root': settings.STATIC_ROOT, 'show_indexes': True}))

rdrf/explorer/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import Group

from rdrf.models import Registry


class Query(models.Model):
    MONGO_SEARCH_TYPES = (
        ('F', 'Find'),
        ('A', 'Aggregation')
    )

    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    
    registry = models.ForeignKey(Registry)
    access_group = models.ManyToManyField(Group)
    
    mongo_search_type = models.CharField(max_length=1, choices=MONGO_SEARCH_TYPES, default='F')
    
    collection = models.CharField(max_length=255, default="cdes")
    criteria = models.TextField(blank=True, null=True)
    projection = models.TextField(blank=True, null=True)
    aggregation = models.TextField(blank=True, null=True)
    
    sql_query = models.TextField()
    created_by = models.CharField(max_length=255, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('explorer_query', kwargs={'query_id': self.pk})

    class Meta:
        ordering = ['title']
        verbose_name_plural = 'Queries'

    def __unicode__(self):
        return unicode(self.title)

rdrf/explorer/forms.py
from django.forms import ModelForm
from models import Query


class QueryForm(ModelForm):

    class Meta:
        model = Query
        fields = [
            'id',
            'title',
            'description',
            
            'registry',
            'access_group',
            'collection',
            'criteria',
            'projection',
            'aggregation',
            'mongo_search_type',
            'sql_query',
            
            'created_by'
        ]

rdrf/explorer/templates/explorer/base.html
<!DOCTYPE HTML>
{% load staticfiles %}
    
<html>
    <head>
        <title>RDRF Reporting Tool</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.21.0/codemirror.min.js"></script>
        <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
        <script src="//code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
        
        <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap-theme.min.css">

        <link rel="stylesheet" href="{% static 'css/explorer.css' %}">
        
        <script src="{% static 'js/jquery.cookies.js' %}"></script>
    </head>
    
    <body>
        
        <nav class="navbar navbar-inverse" role="navigation">
            <div class="container">
                <p class="navbar-brand" href="explorer">RDRF Reporting Tool <sup>{{version}}</sup></p>
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'explorer_main' %}">List</a></li>
                    {% if request.user.is_superuser %}
                        <li><a href="{% url 'explorer_new' %}">New</a></li>
                    {% endif %}
                </ul>

                {% if status %}
                    <p class="navbar-text pull-right"><b><font color="green">Connected</font></p>
                {% else %}
                    <p class="navbar-text pull-right"><b><font color="red">Not connected</font></b></p>
                {% endif%}
            </div>
        </nav>
        
        <div class="container">
            <div class="alert alert-danger" id="response_error" style="display: none;"></div>
            {% if success_msg %}
                <div class="alert alert-success">{{success_msg}}</div>
            {% endif %}
    
            {% if error_msg %}
                <div class="alert alert-danger">{{error_msg}}</div>
            {% endif %}
            
            {% block content %}
            {% endblock %}
        </div>

        <div id="footer">
            <div class="container">
                <h6 class="text-muted">Project developed at <a href="http://ccg.murdoch.edu.au" target="_blank">Centre for Comparative Genomics</a>, <a href="http://www.murdoch.edu.au" target="_blank">Murdoch University</a> &copy <script>document.write(new Date().getFullYear())</script></h6>
            </div>
        </div>
        
        <script>
            $(document).ready(function() {
                if('{{form.mongo_search_type.value}}' == 'F') {
                    $("#mongo-parameters-aggregation").hide();
                } else {
                    $("#mongo-parameters-find").hide();
                }
                
                $("#query-error").hide();
    
                $("#registry-option").change(function(){
                    $("#database").val(this.value);
                });
                
                $("#id_mongo_search_type").change(function() {
                    $("#mongo-parameters-aggregation").toggle();
                    $("#mongo-parameters-find").toggle();
                });

                $('#submit-query').click(function() {
                    $('#results-head').empty();
                    $('#results-body').empty();
                    $.post('', $("#query-form").serialize())
                        .error(function(xhr, textStatus, error) { 
                            $("#response_error").text(textStatus);
                            $("#response_error").fadeIn().delay(3000).fadeOut();
                        })
                        .done(function( data ) {
                            var response = jQuery.parseJSON(data);
                            if ($.isEmptyObject(response)) {
                                $("#response_error").text("No results");
                                $("#response_error").fadeIn().delay(3000).fadeOut();
                                return;
                            }
                            
                            $('#results-head').empty();
                            $('#results-body').empty();

                            $.each(response[0], function(key, value) {
                                $('#results-head').append($("<th></th>").text(key));
                            });
                            
                            $.each(response, function(key, value) {
                                var row = $('<tr></tr>');
                                $.each(value, function(key, value) {
                                    if (value instanceof Array) {
                                        
                                    }
                                    row.append($('<td></td>').text(value));
                                });
                                $('#results-body').append(row);
                        });
                    });
                });

                $('#hide-form-btn').click(function() {
                    $('#query-form-table').toggle("blind", function() {
                        if($('#query-form-table').is( ":visible" )) {
                            $('#hide-form-btn').html('Hide form');
                        } else {
                            $('#hide-form-btn').html('Show form');
                        }
                    });
                });
                
                $('#hide-description-btn').click(function() {
                    $('#query-description').toggle("blind", function() {
                        if($('#query-description').is( ":visible" )) {
                            $('#hide-description-btn').html('Hide description');
                        } else {
                            $('#hide-description-btn').html('Show description');
                        }
                    });
                });
                
                $('#sql-submit-query').click(function(){
                    $("#query-error").hide("blind");
                    $.ajax({
                        url: "{% url 'explorer_sql_query' %}",
                        type: "POST",
                        data: {
                            'sql_query': $('#sql_query').val(),
                            'registry': $('#id_registry').val()
                        },
                        headers: {
                            'X-CSRFToken': $.cookie('{{ csrf_token_name }}')
                        },
                        success: function(data) {
                            response = jQuery.parseJSON(data);
                            if ("error_msg" in response) {
                                $('#query-result-count').empty();
                                $("#query-error").show('blind');
                                $("#query-error").html(response['error_msg']);
                            } else {
                                $('#query-result-count').empty();
                                $('#query-result-count').html("Valid query | <strong>" + response.length + "</strong> record(s) found");
                            }
                        }
                    });
                });
            });
        </script>

    </body>
</html>

rdrf/explorer/templates/explorer/query.html
{% extends "explorer/base.html" %}

{% block content %}    
{{form.errors}}
    <form name='query-form' id='query-form' class="form" method='post'>
        {% csrf_token %}
        <input type="hidden" name="collection" id="collection" value="cdes">
        <input type="hidden" value="{{request.user}}" id="created_by" name="created_by">
    
        <button id="hide-description-btn" type="button" class="btn btn-primary btn-sm">Hide description</button>
        <button id="hide-form-btn" type="button" class="btn btn-primary btn-sm">Hide form</button>

        <div class="pull-right">
            <button type="button" class="btn btn-warning btn-sm" id="sql-submit-query">Validate SQL</button>
            <button type="submit" class="btn btn-primary btn-sm">Save</button>
            <button type="button" name="" id="submit-query" class="btn btn-success btn-sm">Run</button>
        </div>

        <div id="query-description">
            <hr>
            <div class="form-group" style="margin-top: 30px;">
                <input type="text" class="form-control" id="title" name='title' placeholder="Title" value="{{form.title.value|default_if_none:""}}">
            </div>
            
            <div class="form-group">
                <textarea  placeholder="Description" class="form-control" cols="40" id="description" name="description" rows="3">{{form.description.value}}</textarea>
            </div>
        </div>
        
        <div id="query-form-table">        
            <hr/>
    
            <div class="row">
                <div class="col-md-12">    
                    <div class="form-group">
                        <label for="registry">Registry</label>
                            {{form.registry}}
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">    
                    <div class="form-group">
                        <label for="registry">Access</label>
                            {{form.access_group}}
                    </div>
                </div>
            </div>
    
            <div class="row">
                <div class="col-md-12">    
                    <div class="form-group">
                        <label for="mongo_search_type">Mongo Search Type</label>
                            {{form.mongo_search_type}}
                    </div>
                </div>
            </div>
    
            <div class="row">
                <div class="col-md-12">
                    <div class="alert alert-danger" id="query-error">
                    
                    </div>
                </div>
                <div class="col-md-12">
                    <div>
                        <textarea placeholder="Patient SQL query" class="form-control" rows="15" id="sql_query" name="sql_query">{{ form.sql_query.value }}</textarea>
                        <div class="pull-left" id="query-result-count" style="color: green;">
                        </div>
                    </div>    
                </div>
                <div class="col-md-12">
                    <table class="table">
                        <thead>
                            <tr id='query-result-head'></tr>
                        </thead>
                        <tbody id='query-result-body' class="table-hover ">
                        </tbody>
                    </table>
                </div>
            </div>
    
            <div class="row" id="mongo-parameters-find">
                <div class="col-md-6">
                    <textarea class="form-control" cols="40" id="criteria" name="criteria" rows="10">{{form.criteria.value}}</textarea>
                </div>
                <div class="col-md-6">
                    <textarea class="form-control" cols="40" id="projection" name="projection" rows="10">{{form.projection.value}}</textarea>
                </div>
            </div>
            
            <div class="row" id="mongo-parameters-aggregation">
                <div class="col-md-12">
                    <textarea class="form-control" cols="40" id="aggregation" name="aggregation" rows="10">{{form.aggregation.value}}</textarea>
                </div>
            </div>

        </div>
        
    </form>
    
    <hr>

    <table class="table">
        <thead>
            <tr id='results-head'></tr>
        </thead>
        <tbody id='results-body' class="table-hover ">
        </tbody>
    </table>
    
{% endblock %}

rdrf/explorer/templates/explorer/query_download.html
{% extends "explorer/base.html" %}

{% block content %}
    <script>
        $(document).ready(function() {
            $('input[id*=date_]').each(function() {
                $(this).prop('readonly', true);
                $(this).datepicker({
                    "dateFormat": "yy-mm-dd"
                });
            })
        });
    </script>

    {% if messages %}
        <div class="alert alert-danger">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
        </div>
    {% endif %}
    
    <blockquote>
        <p>Required parameters for <i>{{form.title.value}}</i> report</p>
    </blockquote>
    {{user_curator}}
    <form name="params-form" class="form-horizontal" method="post">
        {% csrf_token %}
        {% for param in query_params %}
            <div class="form-group">
                <label for="id_{{param}}" class="col-sm-2 control-label">{{param|capfirst}}</label>
                <div class="col-sm-10">
                    {% if param = 'registry' %}
                        <select id="id_{{param}}" name="{{param}}" class="form-control">
                            <option value=-1>...</option>
                            {% for reg in registry %}
                                <option value={{reg.id}}>{{reg.name}}</option>
                            {% endfor %}
                        </select>
                    {% elif param = 'working_group' %}
                        <select id="id_{{param}}" name="{{param}}" class="form-control">
                            <option value=-1>...</option>
                            {% for wg in working_group %}
                                <option value={{wg.id}}>{{wg.name}}</option>
                            {% endfor %}
                        </select>
                    {% else %}
                        <input type="text" id="id_{{param}}" name="{{param}}" class="form-control">
                    {% endif %}
                </div>
            </div>
        {% endfor %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button class="btn btn-success" type="submit">Download</button>
            </div>
        </div>
    </form>
{% endblock %}

rdrf/explorer/templates/explorer/query_list.html
{% extends "explorer/base.html" %}

{% block content %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th class="col-md-3">Query</th>
                <th class="col-md-3">Download</th>
                <th class="col-md-3">Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
            <tr>
                {% if request.user.is_superuser %}
                    <td><a href="{% url 'explorer_query' object.id %}">{{ object }}</a></td>
                {% else %}
                    <td>{{object}}</td>
                {% endif %}
                <td>
                    <a href="{% url 'explorer_query_download' object.id %}"><i class="glyphicon glyphicon-download" style="font-size: 20px;"></i></a>
                </td>
                <td>
                    {% if request.user.is_superuser %}
                        <i class="glyphicon glyphicon-trash" style="font-size: 18px;" onclick="$('#confirm_' + {{object.id}}).toggle()"></i>
                        <div style="display: none;" id="confirm_{{object.id}}">
                            Are you sure?
                            <a href="{% url 'explorer_query_delete' object.id %}">Yes</a> | 
                            <a onclick="$('#confirm_' + {{object.id}}).toggle()">No</a>
                        </div>
                    {% else %}
                        N/A
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}